---
title: "BST 260 Problem set 3: Logic, reading, guns and geography"
author: "Yixuan Xin"
format: html
editor: visual
---

### Exercise 1.

- $C$ = the coupon is valid

- $P$ = the price is reduced

- $S$ = the shipping is free

The statement can be formalized as

$$C \rightarrow (P \lor S)$$

It is false when $C$ is true and both $P$ and $S$ are wrong. so C cannot lead to $P$ or $S$.

### Exercise 2.

- S = it is sunny

- W = it is warm

- P = picnic is cancelled

$$ (\neg S \wedge \neg W)\rightarrow P$$

It is false if it is not sunny and not warm, but the picnic is not cancelled.

### Exercise 3.

- E = you may enter the contest

- M = you are a member

- P = you have paid the fee

$$E\leftrightarrow (M \lor P)$$

If you enter but the sentence is false, then we should know that you are not a member and you did not paid the fee.

install.packages("dslabs")

### Exercise 4.

This issue is this data is from 2010, which is too old from current year. Moreover, it is not a primary dataset source.

### Exercise 5.

> dim(cdcmurd)
>
> \[1\] 612 5

The output shows that there is 612 rows in the dataset.

### Exercise 6.

One will use the command table(table(head(cdcmurd\$Location,120))) if he wants to know the number of times the states' name appear. The output gives me:

2 3

33 18

It shows that among the first 120 rows, there are 33 states' names appear twice and 18 states' names appear three times.

The results from console give:

> table(table(head(cdcmurd\$Location,153)))
>
> 3 51

> head(table(cdcmurd\$Location))
>
> AK AL AR AZ CA CO
>
> 12 12 12 12 12 12

For the first one, it means there are 51 states' names appear three times in the first 153 rows, and the second one is the number of times each states' names appear. To look at the second one clearer, I use:

> table(table(cdcmurd\$Location))
>
> 12 51

The result shows that for 51 states each name appears 12 times, which is corresponding to 51(12)=612 rows.

From this, I learn that the double table construction is good to show the frequency of number of appearance of each catgeory.

### Exercise 7.

any(is.na(x) tries to find any null value and from a series of boolean and return true if there is at least one null value and vise versa. function(x) is a function and search for null value from x. apply() functions here wants to know in cdcmurd, for each column(with margin=2), find any missing value. In general, this line of code wants to check each column of cdcmurd and see if there is at least one missing value in that column.

> apply(cdcmurd,2,function(x) any(is.na(x))) YEAR Location Death.Rate Deaths URL
>
> FALSE FALSE TRUE FALSE FALSE

The output shows that for Death.Rate column, it has at least one missing value.

### Exercise 8.

This line gets all rows that contains null value in the Death.Rate column in the cdcmurd, and count how many rows are there in total.

> cdcmurd\[which(is.na(cdcmurd\$Death.Rate)),\] \|\> nrow()
>
> \[1\] 28

The result shows there is 28 rows.

### Exercise 9.

> cdcmurd\[which(is.na(cdcmurd\$Death.Rate)),\] \|\> nrow()
>
> \[1\] 28

They both have same result of 28, representing 28 rows having missing values in Death.rate column. Code in exercise 8 gives a numeric value, while code in exercise 9 gives a dataframe and one column called n contains 28.

> median(cdcmurd\$Deaths)
>
> \[1\] 250

### 

> cdcmurd \|\> filter(is.na(Death.Rate)) \|\> + group_by(Location) \|\> summarise(mn=mean(Deaths))
>
> \# A tibble: 6 × 2 Location mn
>
> <chr> <dbl> 1 ME 19\
> 2 ND 14.5 3 NH 17.5 4 RI 19\
> 5 VT 13.7 6 WY 17.2

From the result, we see that the mean value among these states having missing values have a relatively low mean deaths, while the median deaths is 250, which is higher. Therefore, the death rates are missing probably because a low death numbers and cdc may not report a statistically stable death rate.

### Exercise 10.

- Line 1 will filter 204 rows.

- For Line 2, Death.Rate define the y coordinates of the plot.

- the boxplot shows the distribution of a continuous variable and some statistics, including the median, two hinges, two whiskers, and outlying points.

  - Output from R documentation:Description

    The boxplot compactly displays the distribution of a continuous variable. It visualises five summary statistics (the median, two hinges and two whiskers), and all "outlying" points individually.

  - Output from chatbot: The boxplot provides a statistical summary of the distribution of `Death.Rate` for each year. It shows the median, the first and third quartiles, the interquartile range, whiskers, and potential outliers. The beeswarm plot, in contrast, shows the individual observations. Each point represents a location’s death rate, and points with similar values are shifted horizontally to reduce overlap. Thus, the boxplot emphasizes summary statistics, while the beeswarm preserves information about the individual observations and the shape and density of the distribution.

    > myp2 \<- cdcmurd \|\> + filter(YEAR %in% c(2019, 2020, 2021, 2022)) \|\> + ggplot(aes(factor(YEAR), Death.Rate, text = Location)) + + geom_boxplot(outlier.shape = NA) + + geom_beeswarm(alpha = 0.7) + + labs( + x = "Year", + y = "Homicide death rate per 100,000", + title = "Homicide Death Rates by State, 2019–2022" + )
    >
    > ggplotly(myp2)

    The ubdated version contains a better X-axis name called Year, and the Death.Rate is elaborate with unit, and it adds a title. Moreover, it makes the points less dense.

### Exercise 11.

- 11.a: download.file(url, destfile). It can be more interpretable throug separating the ceation of the temorary file and the donload operaition to two lines.

  tf \<- tempfile() download.file("[https://tinyurl.com/randgunlaw",](https://tinyurl.com/randgunlaw",) tf)

- 11.b : read_xlsx() is for reading excel files,with a path as input. 2 means get the second worksheet.

- 11.c: there are 1902 rows.

- 11.d: 1813.

- 11.e: my prompt is: use dplyr and retrieve the earliest valu fo the Effective Date Year column from the lawdat data frame.

  - Code and result:

    > lawdat \|\> + summarize(earliest_year = min(`Effective Date Year`, na.rm = TRUE))
    >
    > \# A tibble: 1 × 1
    >
    > earliest_year
    >
    > <dbl> 1
    >
    > 1813

- 11.f.1: The take home message is the most common change is the implementation of the restrictive gun laws(1241), and the least common change is 'see note' with a permissive effect(2).

- 11.f.2:

  > lawdat \|\> + count(`Type of Change`, Effect, sort = TRUE)
  >
  > \# A tibble: 7 × 3 `Type of Change` Effect n
  >
  > <chr> <chr> <int>
  >
  > 1 Implement Restrictive 1241
  >
  > 2 Modify Restrictive 215
  >
  > 3 Modify Permissive 192
  >
  > 4 Implement Permissive 187
  >
  > 5 Repeal Permissive 59
  >
  > 6 Repeal Restrictive 6
  >
  > 7 See note Permissive 2

From the code, we can see that this result matches with the reference code. I think count() is a brief way to group variables and sort is helpful for listing from the most to the least.

### Exercise 12.

The code first filter the column 'Effect' with only the 'Permissive', and then use summarize to group by 'Effective Date Year', and calculate how many permissive legislative changes happen in that year. Then it uses ggplot() to put the x axis as 'Effective Date Year'. and y axis as the number of changes, and making a dot plot.

It cannot associate each point with certain state because we only group by Effective Date Year instead of by state. Each point represents legislative changes for multiple states instead of only one.

### Exercise 13.

Missouri and Tennessee have the largest frequencies of legislative changes that have “Permissive” effects(15). California state have the largest frequencies of legislative changes that have “Restrictive” effects(73).

> lawdat \|\> + count(Effect, State) \|\> + slice_max(n, by = Effect)
>
> \# A tibble: 3 × 3 Effect State n <chr> <chr> <int>
>
> 1 Permissive Missouri 15
>
> 2 Permissive Tennessee 15
>
> 3 Restrictive California 73

### Exercise 14.

The choice of states: As the exercise 13 shows, California has the largest frequencies of legislative changes that have 'Restrictive' effects, and Missouri and Tennessee have the largest frequencies of legislative changes that have “Permissive” effects. New York has more restrictive changes over permissive changes with a big difference. These states allow for comparison of homicide-rate patterns among states with different changes.

Patterns: From the plot we can see that New York has the lowest death rate, and then California, Missouri, and Tennessee is the highest. The four states all show general similar pattern across years. Missouri has consistenly higher highest death rate than other states, and the highest is around 2021.

To make the result more precise, we could work on data filtering and combination.
